name: Compile JSDocs
on:
  pull_request:
    branches: "main"


jobs:
  compile_JSDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: JSDocs Generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./source/docs
          template: minami
          recurse: true

      - name: Check for changes in docs
        id: check-changes
        run: | 
          HasDiff=$(git status --porcelain)
          echo "::notice file=yeet,line=1,endLine=1,title=tit::$HasDiff"
          echo "::set-output name=docs_changed::$HasDiff"

      - name: commit and push updated docs to the branch
        if: steps.check-changes.outputs.outcome == true
        run: |
          git config --global user.name 'JSDocs action'
          git config --global user.email 'jsdocs@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "Updated JSDocs"
          git push